name: comment Image Analysis on PR

concurrency: 
  group: ${{ github.workflow }}
  
on:
    workflow_run:
        workflows: ["Image Analysis"]
        types:
            - completed

jobs:
  smoketest:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
    steps:
      - name: debug workflow_run
        uses: actions/github-script@v6.4.1
        with:
          script: |
            console.log(JSON.stringify(context))
      - name: print debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check out the source
        uses: actions/checkout@v3
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: image-analysis.yml
          name: image-analysis-comments
          check_artifacts: true
          search_artifacts: true
          if_no_artifact_found: fail
      # set up dependency for github scripts
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install fs
      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var comments =  JSON.parse(fs.readFileSync('./comments.json'));
            console.log(comments);
            while (comments.length > 0) {
            const comment = comments[0];            
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: comment.issue_number,
              body: comment.body
              });
              comments.shift(); 
            } 
      - uses: joutvhu/delete-artifact@v1
        with:
          name: |
            image-analysis-comments
            