name: Image Analysis

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
    pull_request:
    push:
        branches:
        - main

env:
  ORG: timescaledev
  TS_VERSION: main
  PLATFORM: linux/amd64

jobs:
  image-analysis:
    name: PG${{ matrix.pg }}-${{ matrix.type }}
    runs-on: ubuntu-latest
    permissions: {}
    strategy:
      fail-fast: false
      matrix:
        pg: [15]
        type: ["normal", "bitnami"]
    steps:
        # wait till the smoke test is passed
      - name: Pause until all workflows are completed
        uses: willgarcia/workflow-wait-action@0.1.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600
          interval: 10
          initial_delay: 30
          workflows: |
            Smoke Test Docker Image

      - name: Check out the source
        uses: actions/checkout@v3

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Build Docker Image for TimescaleDB
        run: |
          if [ ${{ matrix.type }} == bitnami ]
          then
            cd bitnami
          fi
          make build-docker-cache image PG_VER=pg${{ matrix.pg }} TAG_VERSION=smoketest-image BETA=1

      # set up dependency for github scripts
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install fs

      - name: Download metrics
        if: github.event_name == 'pull_request'
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: image-analysis.yml
          name: image-metric-${{matrix.type}}
          check_artifacts: true
          search_artifacts: true
          if_no_artifact_found: warn
      - name: Download comments
        if: github.event_name == 'pull_request'
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
            workflow: image-analysis.yml
            name: image-analysis-comments
            check_artifacts: true
            search_artifacts: true
            if_no_artifact_found: warn
      - name: Analyse image
        uses: actions/github-script@v6.4.1
        with:
          workspace: ${{ github.workspace }}
          image-type: ${{matrix.type}}
          script: |
            const fs = require('fs')
            const script = require('./image_size.js')
            console.log(script({github, context, exec,core,fs}))

      - name: Hide bot comments
        uses: kanga333/comment-hider@master
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          hide_user_name: "github-actions[bot]"
          hide_reason: "OUTDATED"
          leave_visible: 2
          issue_number: ${{ github.event.number}}

      - uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
            name: image-analysis-comments
            path: comments.json
            if-no-files-found: error
      - uses: actions/upload-artifact@v3
        if: github.event_name == 'push'
        with:
          name: image-metric-${{matrix.type}}
          path: image-metrics-${{matrix.type}}.json
          if-no-files-found: error
